apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-temp-deployment
spec:
  selector:
    matchLabels:
      app: conv-temp
  template:
    metadata:
      labels:
        app: conv-temp
    spec:
      containers:
      - name: conv-temp
        image: arduinni/conversao-temperatura
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conv-temp-service
spec:
  selector:
    app: conv-temp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort